package blackjack;

//@author Alex

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class BlackJack extends javax.swing.JFrame {
    Kontroll kontroll = new Kontroll();

    /**
     * Creates new form Kortstokk
     */
    public BlackJack() {
        initComponents();
        fjernKort();
        setBettingVerdier();
        this.getContentPane().setBackground(Color.decode("#21B94E"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lstKort = new java.awt.List();
        butKort = new javax.swing.JButton();
        lblDealer9 = new javax.swing.JLabel();
        lblDealer8 = new javax.swing.JLabel();
        lblDealer7 = new javax.swing.JLabel();
        lblDealer6 = new javax.swing.JLabel();
        lblDealer5 = new javax.swing.JLabel();
        lblDealer4 = new javax.swing.JLabel();
        lblDealer3 = new javax.swing.JLabel();
        lblDealer2 = new javax.swing.JLabel();
        lblDealer1 = new javax.swing.JLabel();
        lblSpiller9 = new javax.swing.JLabel();
        lblSpiller8 = new javax.swing.JLabel();
        lblSpiller7 = new javax.swing.JLabel();
        lblSpiller6 = new javax.swing.JLabel();
        lblSpiller5 = new javax.swing.JLabel();
        lblSpiller4 = new javax.swing.JLabel();
        lblSpiller3 = new javax.swing.JLabel();
        lblSpiller2 = new javax.swing.JLabel();
        lblSpiller1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTrekk = new javax.swing.JButton();
        btnSta = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        lblDealerSum = new javax.swing.JLabel();
        lblSpillerSum = new javax.swing.JLabel();
        btnInnskudd = new javax.swing.JButton();
        lblChips = new javax.swing.JLabel();
        btnPengerBrukt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblBildekort = new javax.swing.JLabel();
        lblEss = new javax.swing.JLabel();
        lblBildekortProsent = new javax.swing.JLabel();
        lblEssProsent = new javax.swing.JLabel();
        lblSpiller18 = new javax.swing.JLabel();
        lblSpiller17 = new javax.swing.JLabel();
        lblSpiller16 = new javax.swing.JLabel();
        lblSpiller15 = new javax.swing.JLabel();
        lblSpiller14 = new javax.swing.JLabel();
        lblSpiller13 = new javax.swing.JLabel();
        lblSpiller12 = new javax.swing.JLabel();
        lblSpiller11 = new javax.swing.JLabel();
        lblSpiller10 = new javax.swing.JLabel();
        lblSpillerSumSplit = new javax.swing.JLabel();
        btnSplit = new javax.swing.JButton();
        btnDouble = new javax.swing.JButton();
        btnVisKortstokk = new javax.swing.JButton();
        cmbStart = new javax.swing.JComboBox<>();
        btnTrekkSplit = new javax.swing.JButton();
        btnStaSplit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blackjack @Aleksander");
        setBackground(new java.awt.Color(51, 153, 0));
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setPreferredSize(new java.awt.Dimension(720, 500));
        setSize(new java.awt.Dimension(680, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Blackjack");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        lstKort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstKortActionPerformed(evt);
            }
        });
        getContentPane().add(lstKort, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 200));

        butKort.setText("Hent kortstokk");
        butKort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKortActionPerformed(evt);
            }
        });
        getContentPane().add(butKort, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, -1));

        lblDealer9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblDealer9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        lblDealer8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblDealer8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        lblDealer7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblDealer7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        lblDealer6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblDealer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        lblDealer5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblDealer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        lblDealer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblDealer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        lblDealer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblDealer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        lblDealer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblDealer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        lblDealer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblDealer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        lblSpiller9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, -1, -1));

        lblSpiller8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, -1, -1));

        lblSpiller7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, -1, -1));

        lblSpiller6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, -1, -1));

        lblSpiller5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, -1));

        lblSpiller4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, -1));

        lblSpiller3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        lblSpiller2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        lblSpiller1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Dealer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Spiller split");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));

        btnTrekk.setText("Trekk");
        btnTrekk.setEnabled(false);
        btnTrekk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrekkActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrekk, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 120, 40));

        btnSta.setText("Stå");
        btnSta.setEnabled(false);
        btnSta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 120, 40));

        btnStart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStart.setText("Bet");
        btnStart.setEnabled(false);
        btnStart.setMinimumSize(new java.awt.Dimension(63, 33));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, 40));

        lblDealerSum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDealerSum.setText("0");
        getContentPane().add(lblDealerSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 27, -1));

        lblSpillerSum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSpillerSum.setText("0");
        getContentPane().add(lblSpillerSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 30, -1));

        btnInnskudd.setText("Sett inn 100 kr");
        btnInnskudd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInnskuddActionPerformed(evt);
            }
        });
        getContentPane().add(btnInnskudd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 120, -1));

        lblChips.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblChips.setText("Chips: 0");
        getContentPane().add(lblChips, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        btnPengerBrukt.setText("Se penger brukt");
        btnPengerBrukt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengerBruktActionPerformed(evt);
            }
        });
        getContentPane().add(btnPengerBrukt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 120, -1));

        jLabel3.setText("Antall ess:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel5.setText("Antall tiere:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lblBildekort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBildekort.setText("0");
        getContentPane().add(lblBildekort, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 337, -1, 20));

        lblEss.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEss.setText("0");
        getContentPane().add(lblEss, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 397, -1, 20));

        lblBildekortProsent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBildekortProsent.setText("(0 %)");
        getContentPane().add(lblBildekortProsent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        lblEssProsent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEssProsent.setText("(0 %)");
        getContentPane().add(lblEssProsent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lblSpiller18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller18, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, -1, -1));

        lblSpiller17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, -1, -1));

        lblSpiller16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, -1, -1));

        lblSpiller15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, -1, -1));

        lblSpiller14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, -1, -1));

        lblSpiller13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, -1, -1));

        lblSpiller12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, -1));

        lblSpiller11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, -1));

        lblSpiller10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png"))); // NOI18N
        getContentPane().add(lblSpiller10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, -1));

        lblSpillerSumSplit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSpillerSumSplit.setText("0");
        getContentPane().add(lblSpillerSumSplit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 30, -1));

        btnSplit.setText("Split");
        btnSplit.setEnabled(false);
        btnSplit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSplit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 120, 40));

        btnDouble.setText("Double down");
        btnDouble.setEnabled(false);
        btnDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleActionPerformed(evt);
            }
        });
        getContentPane().add(btnDouble, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 120, 40));

        btnVisKortstokk.setText("Vis kortstokk");
        btnVisKortstokk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisKortstokkActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisKortstokk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, -1));

        cmbStart.setBackground(new java.awt.Color(240, 240, 240));
        cmbStart.setEnabled(false);
        cmbStart.setMinimumSize(new java.awt.Dimension(43, 25));
        cmbStart.setPreferredSize(new java.awt.Dimension(43, 25));
        cmbStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStartActionPerformed(evt);
            }
        });
        getContentPane().add(cmbStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 60, 40));

        btnTrekkSplit.setText("Trekk");
        btnTrekkSplit.setEnabled(false);
        btnTrekkSplit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrekkSplitActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrekkSplit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 120, 40));

        btnStaSplit.setText("Stå");
        btnStaSplit.setEnabled(false);
        btnStaSplit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaSplitActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaSplit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Spiller");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butKortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKortActionPerformed
        kontroll.leggTilKort();
        lastInnKort();
        btnStart.setEnabled(true);
        cmbStart.setEnabled(true);
        btnTrekk.setEnabled(false);
        btnSta.setEnabled(false);
        lblEss.setText(String.valueOf(kontroll.essigjen));
        lblBildekort.setText(String.valueOf(kontroll.bildekortigjen));
        beregnProsent();
        resetVerdier();
    }//GEN-LAST:event_butKortActionPerformed

    private void lastInnKort(){
        lstKort.removeAll();
        Object[][] liste = kontroll.hentKortstokk();
        int antall = kontroll.hentAntallKort();
        for(int i=0; i<antall; i++){
            lstKort.add(liste[0][i].toString());
        }
    }
    
    private void lstKortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstKortActionPerformed
        Object[][] liste = kontroll.hentKortstokk();
        String kort = "";
        String verdi = "";
        int antall = kontroll.hentAntallKort();
        for(int i=0; i<antall; i++){
            if(liste[0][i].toString().equals(evt.getActionCommand())){
                kort = liste[0][i].toString();
                verdi = liste[1][i].toString();
            }
        }
        if(verdi.equals("11")){
            verdi = "11 eller 1";
        }
        JOptionPane.showMessageDialog(null, "Kort: "+kort+"\nVerdi: "+verdi);
    }//GEN-LAST:event_lstKortActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if(kontroll.penger < Integer.parseInt(cmbStart.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Du må ha flere chips for å spille.");
        } else {
            int bet = Integer.parseInt(cmbStart.getSelectedItem().toString());
            kontroll.penger -= bet;
            lblChips.setText("Chips: "+String.valueOf(kontroll.penger));
            resetVerdier();
            //Henter kort 1 til dealer
            kontroll.sjekkKortstokk();
            kontroll.dealerTotal(kontroll.seNesteVerdi());
            if(kontroll.seNesteVerdi() == 11){
                kontroll.dealerEss();
            }
            lblDealer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
            lblDealer1.setVisible(true);
            kontroll.dealerKort();
            
            //Henter kort 2 til dealer
            kontroll.sjekkKortstokk();
            kontroll.dealerkortverdi = kontroll.seNesteVerdi();
            if(kontroll.seNesteVerdi() == 11){
                kontroll.dealerEss();
            }
            kontroll.dealerkort = kontroll.nesteKort();
            lblDealer2.setVisible(true);
            kontroll.dealerKort();

            //Henter kort 1 til spiller
            kontroll.sjekkKortstokk();
            kontroll.spillerTotal(kontroll.seNesteVerdi());
            if(kontroll.seNesteVerdi() == 11){
                kontroll.spillerEss();
            }
            lblSpiller1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
            lblSpiller1.setVisible(true);
            kontroll.spillerKort();

            //Henter kort 2 til spiller
            kontroll.sjekkKortstokk();
            kontroll.spillerTotal(kontroll.seNesteVerdi());
            kontroll.splitverdi += kontroll.seNesteVerdi();
            kontroll.splitkort = kontroll.seNesteKort();
            if(kontroll.seNesteVerdi() == 11){
                kontroll.spillerEss();
            }
            lblSpiller2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
            lblSpiller2.setVisible(true);
            kontroll.spillerKort();
            lblDealerSum.setText(String.valueOf(kontroll.sumdealer));
            lblSpillerSum.setText(String.valueOf(kontroll.sumspiller));
            lblSpillerSumSplit.setText(String.valueOf(kontroll.splitverdi));
            btnTrekk.setEnabled(true);
            btnDouble.setEnabled(true);
            btnStart.setEnabled(false);
            cmbStart.setEnabled(false);
            btnSta.setEnabled(true);
            btnSplit.setEnabled(true);
            spillerMax();
            lastInnKort();
            lblBildekort.setText(String.valueOf(kontroll.bildekortigjen));
            lblEss.setText(String.valueOf(kontroll.essigjen));
            beregnProsent();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnTrekkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrekkActionPerformed
        //Henter kort til spiller
        kontroll.sjekkKortstokk();
        kontroll.spillerTotal(kontroll.seNesteVerdi());
        if(kontroll.seNesteVerdi() == 11){
            kontroll.spillerEss();
        }
        switch(kontroll.kortspiller){
            case 1:
                lblSpiller2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller2.setVisible(true);
                kontroll.spillerKort();
                break;
            case 2:
                lblSpiller3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller3.setVisible(true);
                kontroll.spillerKort();
                break;
            case 3:
                lblSpiller4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller4.setVisible(true);
                kontroll.spillerKort();
                break;
            case 4:
                lblSpiller5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller5.setVisible(true);
                kontroll.spillerKort();
                break;
            case 5:
                lblSpiller6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller6.setVisible(true);
                kontroll.spillerKort();
                break;
            case 6:
                lblSpiller7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller7.setVisible(true);
                kontroll.spillerKort();
                break;
            case 7:
                lblSpiller8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller8.setVisible(true);
                kontroll.spillerKort();
                break;
            case 8:
                lblSpiller9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller9.setVisible(true);
                kontroll.spillerKort();
                break;
        }
        lblSpillerSum.setText(String.valueOf(kontroll.sumspiller));
        spillerMax();
        lastInnKort();
        lblBildekort.setText(String.valueOf(kontroll.bildekortigjen));
        lblEss.setText(String.valueOf(kontroll.essigjen));
        beregnProsent();
        btnDouble.setEnabled(false);
        btnSplit.setEnabled(false);
    }//GEN-LAST:event_btnTrekkActionPerformed

    private void btnStaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaActionPerformed
        if(kontroll.spillersplit){
            btnTrekkSplit.setEnabled(true);
            btnStaSplit.setEnabled(true);
            btnTrekk.setEnabled(false);
            btnDouble.setEnabled(false);
            btnSta.setEnabled(false);
            kontroll.kortspiller = 2;
        } else {
            kontroll.dealerTotal(kontroll.dealerkortverdi);
            trekkDealer();
            btnStart.setEnabled(true);
            cmbStart.setEnabled(true);
            btnTrekk.setEnabled(false);
            btnDouble.setEnabled(false);
            btnSta.setEnabled(false);
            lastInnKort();
            resultat();
        }
    }//GEN-LAST:event_btnStaActionPerformed

    private void btnInnskuddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInnskuddActionPerformed
        kontroll.penger += 100;
        kontroll.pengerbrukt += 100;
        lblChips.setText("Chips: "+String.valueOf(kontroll.penger));
    }//GEN-LAST:event_btnInnskuddActionPerformed

    private void btnPengerBruktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengerBruktActionPerformed
        JOptionPane.showMessageDialog(null, "Du har brukt "+kontroll.pengerbrukt+" kr\nDet er spilt "+kontroll.runderspilt+" runder");
    }//GEN-LAST:event_btnPengerBruktActionPerformed

    private void btnSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplitActionPerformed
        if(kontroll.penger < Integer.parseInt(cmbStart.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Du har ikke nok chips til split.");
        } else {
            kontroll.spillersplit = true;
            kontroll.kortspiller -= 1;
            btnTrekkSplit.setVisible(true);
            btnStaSplit.setVisible(true);
            jLabel4.setVisible(true);
            btnTrekkSplit.setEnabled(false);
            btnStaSplit.setEnabled(false);
            lblSpillerSumSplit.setVisible(true);
            lblSpiller10.setVisible(true);
            lblSpiller11.setVisible(true);
            lblSpiller10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.splitkort+".png")));
            lblSpiller11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
            lblSpiller2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
            kontroll.sumspiller -= kontroll.splitverdi;
            lblSpillerSum.setText(String.valueOf(kontroll.sumspiller));
            btnSplit.setEnabled(false);
            btnDouble.setEnabled(false);
            int bet = Integer.parseInt(cmbStart.getSelectedItem().toString());
            kontroll.penger -= bet;
            lblChips.setText("Chips: "+String.valueOf(kontroll.penger));
        }
    }//GEN-LAST:event_btnSplitActionPerformed

    private void btnDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoubleActionPerformed
        if(kontroll.penger < Integer.parseInt(cmbStart.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Du har ikke nok chips til double down.");
        } else {
            btnTrekk.setEnabled(false);
            btnSplit.setEnabled(false);
            btnTrekkActionPerformed(evt);
            kontroll.spillerdouble = true;
            int bet = Integer.parseInt(cmbStart.getSelectedItem().toString());
            kontroll.penger -= bet;
            lblChips.setText("Chips: "+String.valueOf(kontroll.penger));
        }
    }//GEN-LAST:event_btnDoubleActionPerformed

    private void btnVisKortstokkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisKortstokkActionPerformed
        if(lstKort.isVisible()){
            lstKort.setVisible(false);
            btnVisKortstokk.setText("Vis kortstokk");
        } else {
            lstKort.setVisible(true);
            btnVisKortstokk.setText("Skjul kortstokk");
        }
    }//GEN-LAST:event_btnVisKortstokkActionPerformed

    private void cmbStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStartActionPerformed
        
    }//GEN-LAST:event_cmbStartActionPerformed

    private void btnTrekkSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrekkSplitActionPerformed
        //Henter kort til spiller
        kontroll.sjekkKortstokk();
        kontroll.spillerSplitTotal(kontroll.seNesteVerdi());
        if(kontroll.seNesteVerdi() == 11){
            kontroll.spillerEss();
        }
        switch(kontroll.kortspiller){
            case 1:
                lblSpiller10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller10.setVisible(true);
                kontroll.spillerKort();
                break;
            case 2:
                lblSpiller11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller11.setVisible(true);
                kontroll.spillerKort();
                break;
            case 3:
                lblSpiller12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller12.setVisible(true);
                kontroll.spillerKort();
                break;
            case 4:
                lblSpiller13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller13.setVisible(true);
                kontroll.spillerKort();
                break;
            case 5:
                lblSpiller14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller14.setVisible(true);
                kontroll.spillerKort();
                break;
            case 6:
                lblSpiller15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller15.setVisible(true);
                kontroll.spillerKort();
                break;
            case 7:
                lblSpiller16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller16.setVisible(true);
                kontroll.spillerKort();
                break;
            case 8:
                lblSpiller17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                lblSpiller17.setVisible(true);
                kontroll.spillerKort();
                break;
        }
        lblSpillerSumSplit.setText(String.valueOf(kontroll.splitverdi));
        spillerMaxSplit();
        lastInnKort();
        lblBildekort.setText(String.valueOf(kontroll.bildekortigjen));
        lblEss.setText(String.valueOf(kontroll.essigjen));
        beregnProsent();
    }//GEN-LAST:event_btnTrekkSplitActionPerformed

    private void btnStaSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaSplitActionPerformed
        kontroll.dealerTotal(kontroll.dealerkortverdi);
        trekkDealer();
        btnStart.setEnabled(true);
        cmbStart.setEnabled(true);
        btnTrekk.setEnabled(false);
        btnDouble.setEnabled(false);
        btnSta.setEnabled(false);
        btnTrekkSplit.setEnabled(false);
        btnStaSplit.setEnabled(false);
        lastInnKort();
        resultat();
        resultatsplit();
    }//GEN-LAST:event_btnStaSplitActionPerformed

    private void trekkDealer(){
        if(dealerMax()){
            kontroll.sjekkKortstokk();
            kontroll.dealerTotal(kontroll.seNesteVerdi());
            if(kontroll.seNesteVerdi() == 11){
                kontroll.dealerEss();
            }
            switch(kontroll.kortdealer){
                case 2:
                    lblDealer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                    lblDealer3.setVisible(true);
                    kontroll.dealerKort();
                    break;
                case 3:
                    lblDealer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                    lblDealer4.setVisible(true);
                    kontroll.dealerKort();
                    break;
                case 4:
                    lblDealer5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                    lblDealer5.setVisible(true);
                    kontroll.dealerKort();
                    break;
                case 5:
                    lblDealer6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                    lblDealer6.setVisible(true);
                    kontroll.dealerKort();
                    break;
                case 6:
                    lblDealer7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                    lblDealer7.setVisible(true);
                    kontroll.dealerKort();
                    break;
                case 7:
                    lblDealer8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                    lblDealer8.setVisible(true);
                    kontroll.dealerKort();
                    break;
                case 8:
                    lblDealer9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.nesteKort()+".png")));
                    lblDealer9.setVisible(true);
                    kontroll.dealerKort();
                    break;
            }
            lblDealerSum.setText(String.valueOf(kontroll.sumdealer));
            lblBildekort.setText(String.valueOf(kontroll.bildekortigjen));
            lblEss.setText(String.valueOf(kontroll.essigjen));
            beregnProsent();
            trekkDealer();
        }
    }
    
    private void beregnProsent(){
        if(kontroll.hentAntallKort() == 0){
            lblBildekortProsent.setText("(0 %)");
            lblEssProsent.setText("(0 %)");
        } else {
            DecimalFormat decimalformat = new DecimalFormat("#.##");
            double antallkort = (double)kontroll.hentAntallKort();
            double antalless = (double)kontroll.essigjen;
            double antallbildekort = (double)kontroll.bildekortigjen;
            double prosentess = antalless/antallkort*100;
            double prosentbildekort = antallbildekort/antallkort*100;
            lblBildekortProsent.setText("("+String.valueOf(decimalformat.format(prosentbildekort))+" %)");
            lblEssProsent.setText("("+String.valueOf(decimalformat.format(prosentess))+" %)");
        }
    }
    
    public void resetVerdier(){
        kontroll.sumspiller = 0;
        kontroll.splitverdi = 0;
        lblSpillerSum.setText("0");
        lblSpillerSumSplit.setText("0");
        lblDealerSum.setText("0");
        kontroll.sumdealer = 0;
        kontroll.essspiller = 0;
        kontroll.essdealer = 0;
        kontroll.kortspiller = 0;
        kontroll.kortdealer = 0;
        kontroll.dealerkortverdi = 0;
        kontroll.spillerdouble = false;
        kontroll.spillersplit = false;
        kontroll.dealerkort = null;
        kontroll.splitkort = null;
        lblDealer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblDealer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblDealer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblDealer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblDealer5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblDealer6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        fjernKort();
    }
    
    private void fjernKort(){
        lblDealer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblDealer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblDealer3.setVisible(false);
        lblDealer4.setVisible(false);
        lblDealer5.setVisible(false);
        lblDealer6.setVisible(false);
        lblDealer7.setVisible(false);
        lblDealer8.setVisible(false);
        lblDealer9.setVisible(false);
        lblSpiller1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/bakside.png")));
        lblSpiller3.setVisible(false);
        lblSpiller4.setVisible(false);
        lblSpiller5.setVisible(false);
        lblSpiller6.setVisible(false);
        lblSpiller7.setVisible(false);
        lblSpiller8.setVisible(false);
        lblSpiller9.setVisible(false);
        lblSpiller10.setVisible(false);
        lblSpiller11.setVisible(false);
        lblSpiller12.setVisible(false);
        lblSpiller13.setVisible(false);
        lblSpiller14.setVisible(false);
        lblSpiller15.setVisible(false);
        lblSpiller16.setVisible(false);
        lblSpiller17.setVisible(false);
        lblSpiller18.setVisible(false);
        lblSpillerSumSplit.setVisible(false);
        jLabel4.setVisible(false);
        btnTrekkSplit.setVisible(false);
        btnStaSplit.setVisible(false);
    }
    
    private void setBettingVerdier(){
        String[] bets = {"20", "50", "100", "200"};
        for(int i=0; i<4; i++){
            cmbStart.addItem(bets[i]);
        }
        lstKort.setVisible(false);
    }
    
    private void spillerMax(){
        if(kontroll.sumspiller > 21 && kontroll.essspiller > 0){
            kontroll.sumspiller = kontroll.sumspiller - 10;
            lblSpillerSum.setText(String.valueOf(kontroll.sumspiller));
            kontroll.essspiller--;
            spillerMax();
        }
        if(kontroll.sumspiller > 20){
            btnTrekk.setEnabled(false);
            btnDouble.setEnabled(false);
        }
    }
    
    private void spillerMaxSplit(){
        if(kontroll.splitverdi > 21 && kontroll.essspiller > 0){
            kontroll.splitverdi = kontroll.splitverdi - 10;
            lblSpillerSumSplit.setText(String.valueOf(kontroll.splitverdi));
            kontroll.essspiller--;
            spillerMax();
        }
        if(kontroll.splitverdi > 20){
            btnTrekkSplit.setEnabled(false);
        }
    }
    
    private boolean dealerMax(){
        if(kontroll.sumspiller > 21){
            return false;
        } else {
            lblDealer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Min_Kort/"+kontroll.dealerkort+".png")));
            lblDealerSum.setText(String.valueOf(kontroll.sumdealer));
        }
        if(kontroll.sumdealer > 21 && kontroll.essdealer > 0){
            kontroll.sumdealer = kontroll.sumdealer - 10;
            lblDealerSum.setText(String.valueOf(kontroll.sumdealer));
            kontroll.essdealer--;
            dealerMax();
        }
        if(kontroll.sumdealer < 17){
            return true;
        } else {
            return false;
        }
    }
    
    private void resultat(){
        int bet = Integer.parseInt(cmbStart.getSelectedItem().toString());
        if(kontroll.sumdealer == kontroll.sumspiller){
            if(kontroll.spillersplit){
                JOptionPane.showMessageDialog(null, "Uavgjort på første hånden");
            } else {
                JOptionPane.showMessageDialog(null, "Uavgjort");
            }
            if(kontroll.spillerdouble == false){
                kontroll.penger += bet;
            } else {
                kontroll.penger += bet*2;
            }
            kontroll.runderspilt += 1;
            lblChips.setText("Chips: "+String.valueOf(kontroll.penger));
        } else if(kontroll.sumdealer <= 21 && kontroll.sumdealer > kontroll.sumspiller){
            if(kontroll.spillersplit){
                JOptionPane.showMessageDialog(null, "Dealer vant første hånden");
            } else {
                JOptionPane.showMessageDialog(null, "Dealer vant");
            }
            kontroll.runderspilt += 1;
        } else if(kontroll.sumdealer <= 21 && kontroll.sumspiller > 21){
            if(kontroll.spillersplit){
                JOptionPane.showMessageDialog(null, "Dealer vant første hånden");
            } else {
                JOptionPane.showMessageDialog(null, "Dealer vant");
            }
            kontroll.runderspilt += 1;
        } else {
            if(kontroll.spillersplit){
                JOptionPane.showMessageDialog(null, "Du vant første hånden");
            } else {
                JOptionPane.showMessageDialog(null, "Du vant");
            }
            if(kontroll.spillerdouble == false){
                kontroll.penger += bet*2;
            } else {
                kontroll.penger += bet*4;
            }
            kontroll.runderspilt += 1;
            lblChips.setText("Chips: "+String.valueOf(kontroll.penger));
        }
    }
    
    private void resultatsplit(){
        int bet = Integer.parseInt(cmbStart.getSelectedItem().toString());
        if(kontroll.sumdealer == kontroll.splitverdi){
            if(kontroll.spillersplit){
                JOptionPane.showMessageDialog(null, "Uavgjort på andre hånden");
            } else {
                JOptionPane.showMessageDialog(null, "Uavgjort");
            }
            if(kontroll.spillerdouble == false){
                kontroll.penger += bet;
            } else {
                kontroll.penger += bet*2;
            }
            kontroll.runderspilt += 1;
            lblChips.setText("Chips: "+String.valueOf(kontroll.penger));
        } else if(kontroll.sumdealer <= 21 && kontroll.sumdealer > kontroll.splitverdi){
            if(kontroll.spillersplit){
                JOptionPane.showMessageDialog(null, "Dealer vant andre hånden");
            } else {
                JOptionPane.showMessageDialog(null, "Dealer vant");
            }
            kontroll.runderspilt += 1;
        } else if(kontroll.sumdealer <= 21 && kontroll.splitverdi > 21){
            if(kontroll.spillersplit){
                JOptionPane.showMessageDialog(null, "Dealer vant andre hånden");
            } else {
                JOptionPane.showMessageDialog(null, "Dealer vant");
            }
            kontroll.runderspilt += 1;
        } else {
            if(kontroll.spillersplit){
                JOptionPane.showMessageDialog(null, "Du vant andre hånden");
            } else {
                JOptionPane.showMessageDialog(null, "Du vant");
            }
            if(kontroll.spillerdouble == false){
                kontroll.penger += bet*2;
            } else {
                kontroll.penger += bet*4;
            }
            lblChips.setText("Chips: "+String.valueOf(kontroll.penger));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJack().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDouble;
    private javax.swing.JButton btnInnskudd;
    private javax.swing.JButton btnPengerBrukt;
    private javax.swing.JButton btnSplit;
    private javax.swing.JButton btnSta;
    private javax.swing.JButton btnStaSplit;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnTrekk;
    private javax.swing.JButton btnTrekkSplit;
    private javax.swing.JButton btnVisKortstokk;
    private javax.swing.JButton butKort;
    private javax.swing.JComboBox<String> cmbStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBildekort;
    private javax.swing.JLabel lblBildekortProsent;
    private javax.swing.JLabel lblChips;
    private javax.swing.JLabel lblDealer1;
    private javax.swing.JLabel lblDealer2;
    private javax.swing.JLabel lblDealer3;
    private javax.swing.JLabel lblDealer4;
    private javax.swing.JLabel lblDealer5;
    private javax.swing.JLabel lblDealer6;
    private javax.swing.JLabel lblDealer7;
    private javax.swing.JLabel lblDealer8;
    private javax.swing.JLabel lblDealer9;
    private javax.swing.JLabel lblDealerSum;
    private javax.swing.JLabel lblEss;
    private javax.swing.JLabel lblEssProsent;
    private javax.swing.JLabel lblSpiller1;
    private javax.swing.JLabel lblSpiller10;
    private javax.swing.JLabel lblSpiller11;
    private javax.swing.JLabel lblSpiller12;
    private javax.swing.JLabel lblSpiller13;
    private javax.swing.JLabel lblSpiller14;
    private javax.swing.JLabel lblSpiller15;
    private javax.swing.JLabel lblSpiller16;
    private javax.swing.JLabel lblSpiller17;
    private javax.swing.JLabel lblSpiller18;
    private javax.swing.JLabel lblSpiller2;
    private javax.swing.JLabel lblSpiller3;
    private javax.swing.JLabel lblSpiller4;
    private javax.swing.JLabel lblSpiller5;
    private javax.swing.JLabel lblSpiller6;
    private javax.swing.JLabel lblSpiller7;
    private javax.swing.JLabel lblSpiller8;
    private javax.swing.JLabel lblSpiller9;
    private javax.swing.JLabel lblSpillerSum;
    private javax.swing.JLabel lblSpillerSumSplit;
    private java.awt.List lstKort;
    // End of variables declaration//GEN-END:variables
}
